### PR TITLE
Various fixes for VSCode integration

### PR DESCRIPTION
**Pull request by wmanley**
And a few other tidyups. Tests can once again be discovered and run now.

### CODE REVIEW

**Review by drothlis — APPROVED** [review]
Thanks! Nice improvements and the fixes for VS Code weren't too intrusive. I do wonder if it's worth maintaining this approach -- I suppose we'll wait to see how long until VS Code breaks this again, and re-evaluate.

Have you tested this change with PyCharm?

For the record, previous VS Code breakages: #35.
Previous pytest breakages: https://github.com/pytest-dev/pytest/issues/5277.

**Comment by wmanley** [comment]
> I do wonder if it's worth maintaining this approach -- I suppose we'll wait to see how long until VS Code breaks this again, and re-evaluate.

IMO the maintenance cost is worth it for the functionality - the question is whether there is a better way. `stbt-docker` was a worse experience, and also hard to maintain. A new VSCode plugin feels like it would be a lot of work. I wonder if there are any other options?  Perhaps patch the VSCode-python plugin to support this use case directly? 

> Have you tested this change with PyCharm?

No, but I don't think it's too risky.  I'll test it if I can do it quickly.

**Comment by drothlis** [comment]
> Perhaps patch the VSCode-python plugin to support this use case directly?

Patch it to do what, specifically? Obviously they won't want to add "stbt-rig" support at the same level as pytest / unittest / nose, as it's too specialised.

Maybe something where you can configure the following:

- A regex to match lines in the source file where it should display a "[Code Lens]" (those inline links like "Run Test").
- The text to display in the Code Lens.
- A command line to run when clicking the Code Lens (with `$1` etc replaced with capture groups from the regex).

It wouldn't even be specific to Python so it would make more sense as a separate extension. Maybe it wouldn't be so hard, there are other open-source extensions to copy from, e.g. [rust-test-lens](https://github.com/hdevalke/rust-test-lens/blob/master/src/RustCodeLensProvider.ts) on [rest-code-lens](https://github.com/dtinth/vscode-rest-code-lens).

[Code Lens]: https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup

**Comment by wmanley** [comment]
> Patch it to do what, specifically?

The VSCode Python plugin is split into two parts. The plugin proper is written in TypeScript, which then invokes Python to actually run the test or do discovery, or run some code in the debugger. The interface between the two is command line arguments and JSON over stdout to send the results.

The Python bit calls the implementation specific (pytest, nose, etc) and sends the results back. If I were to want stbt_rig support I'd define this a Python base class that encapsulates this and implement that.  Then the trick would be to extend the VSCode-Python such that it can load such an interface from a package of our choosing: in this case stbt-rig.

**Pull request merged**
